#!/usr/bin/env bash 

# /dev/null

# download latest wordpress 
echo "downloading wordpress"
wget http://wordpress.org/latest.tar.gz -q 

# unpack tarball
echo "unpacking wordpress"
tar xfz latest.tar.gz 

# mkdir in the localhost dir
echo "making dir /var/www/html/$1"  
sudo mkdir /var/www/html/$1 

# move files there 
echo "moving wordpress to dir /var/www/html/$1"
sudo mv wordpress/*  /var/www/html/$1 


# delete leftovers 
echo "removing download leftovers"
rm -fr latest.tar.gz wordpress 


# cd to the new installation dir
echo "cd to /var/www/html"

cd /var/www/html

# setting pemissions 

echo $pwd  

echo "setting user permissions"
sudo chown $USER  -R $1

cd $1

echo $pwd  

echo "setting apache permissions"
sudo chown www-data:www-data wp-content 

code -n . 
